services:
  postgres:
    image: postgres:16
    container_name: pg_practica1
    restart: always
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: practica1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: